### ISSUE TITLE
Question: Usage of Token to Clone

### ISSUE THREAD

**Issue by oliveirafilipe** [daspn/private-actions-checkout#8]
Hi Daspn, is in the Roadmap the use of a Personal access token (PAT) to fetch the repository, instead of SSH Key?

I think PAT is a common way to grant access to target repo, since we can see it in the  actions/checkout action 
https://github.com/actions/checkout#checkout-multiple-repos-private

and other solutions for private actions usage
https://github.com/bagbyte/use-private-action#usage

**Comment by daspn** [comment]
Hi @oliveirafilipe, that's a good suggestion and it's definitely on the roadmap. This action was conceived to solve our internal problem with the lack of built-in private actions and the SSH strategy was used because that's the way we already clone some private Terraform and Ansible modules while running our IaC. Unfortunately I'm currently busy enough to evolve this action but I will try to take a closer look as soon as possible. If you feel comfortable, please fork the repo and send us a PR! :) Best,
